version: '3.4'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontendapp:ver1
    container_name: frontend-app
    ports:
      - "8080:8080"
    volumes:
      - '.:/app'
      - '/app/node_modules'

